config/routes.rb
Joslynrosbrookdotcom::Application.routes.draw do

  root 'static_pages#index'

  get '/pindd' => 'static_pages#pindd'
  get '/ploppycat' => 'static_pages#ploppy_cat'
  get '/solarsystem' => 'static_pages#solar_system'
  get '/sync-cats' => 'static_pages#sync_cats', as: "sync_cats"

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  end

  def ploppy_cat
  end

  def pindd
  end

  def solar_system
  end

  def sync_cats
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def body_class
    [controller_name, action_name].join('-')
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Joslyn Rosbrook | Developer</title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <link href='http://fonts.googleapis.com/css?family=Candal|Allerta|Spinnaker' rel='stylesheet' type='text/css'>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
  <script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-49333025-1', 'joslynrosbrook.com');
  ga('send', 'pageview');

</script>
</head>
<body class="<%= body_class %>">
  <header>
    <nav>
      <ul>
        <li><%= link_to "Projects", root_path %></li>
        <li><%= link_to "About", "#", class:'about-link' %></li>
        <li><%= link_to "Musings", "http://blog.joslynrosbrook.com/" %></li>
      <ul>
    </nav>
  </header>
  <section id="about-wrap">
  <div class="primary">
    <h1>Hi there!</h1>
    <p>My name is Joslyn. I'm a Seattle based Ruby on Rails developer with a <strong>strong</strong> affinity for the front-end and user experience.</p>
    <div id="about-photo">
      <%= image_tag("cssisawesome.jpg", alt: "Joslyn Rosbrook")%>
    </div>
    <p>When I'm not on my computer, you can find me on my yoga mat or curled up under a pile of blankets (but usually the computer finds its way there as well).</p>
  </div>
  <div class="secondary">
    <p>I recently graduated Code Fellows and now I'd like to use my passion for design and development to help <b>YOU</b>!</p>
      <h3>Let's chat?</h3>
         <div class="social-icons">
          <a href="http://www.twitter.com/joslynrosbrook" style="color:dodgerblue; font-size: 50px" class="fa fa-twitter"></a>
          <a href="http://www.github.com/meowmaste" style="color:indigo; font-size: 50px" class="fa fa-github"></a>
          <a href="http://www.linkedin.com/in/joslynrosbrook" style=" color:dimgray; font-size: 50px" class="fa fa-linkedin"></a>
        </div>
        <h5 class="email"><a href="mailto:jrosbrook@gmail.com">jrosbrook@gmail.com</a></h5>
  </div>
</section>
  <%= yield %>
  <footer>
    <p>&copy; 2014 Joslyn Rosbrook.</p>
  </footer>

</body>
</html>

app/views/static_pages/index.html.erb
<section id="portfolio-wrap">
  <h1>Featured Work</h1>
  <h2>from the developer, <a class="about-link" href="#">Joslyn Rosbrook</a></h2>
  <ul id="gallery">
    <li>
      <%= link_to pindd_path do %>
        PINDD
        <%= image_tag("pindd.png", alt: "Post-It Note Driven Development")%>
      <% end %>
    </li>
    <li>
      <%= link_to solarsystem_path do %>
        Solar System
        <%= image_tag("solarsystem.png", alt: "Solar System")%>
      <% end %>
    </li>
    <li>
      <%= link_to ploppycat_path do %>
        Ploppy Cat
        <%= image_tag("ploppycat.png", alt: "Play Ploppy Cat")%>
      <% end %>
    </li>
    <li>
      <%= link_to sync_cats_path do %>
        Sync Cats
        <%= image_tag("sync-cats.png", alt: "Sync Cats")%>
      <% end %>
    </li>
  </ul>
</section>

app/views/static_pages/pindd.html.erb
<div class="project">
  <header class="project-header">
    <h1>PINDD: Post-It Note Driven Development</h1>
      <h3>An app in which ideas and reminders can be shared between users on virtual sticky notes.</h3>
  </header>
  <section class="project-details">
    <div class="img-container", style="background-color:#D79BEE;">
      <%= image_tag("pindd.png", class: "main-photo", alt: "Post-It Note Driven Development")%>
      <%= image_tag("pindd-phone.png", class: "mobile-photo", alt: "Phone Layout")%>
    </div>
    <div class="text-block">
      <p><a href="https://pindd.herokuapp.com/">This is an app</a> I made in project week with fellow classmate, <a href="https://github.com/orangeninjamidget">Lillian Ng</a>, for <a href="http://codefellows.org">Code Fellows.</a> We enjoyed the app so much we decided to continue adding features after our course ended!</p>
      <p>This app allows users to manage tasks and ideas in a dynamic way. Users can sign in and create tasks as sticky notes on an online display board. Users can also create groups and add other users in order to share tasks. Users can see real-time updates as tasks shared with other users are checked off or deleted.</p>
      <p>The app is responsive and built using Ruby on Rails and hosted on Heroku. Other technologies used include: HTML5 Web Sockets, CSS3, Bootstrap, Travis Continuous Integration, jQuery, and JavaScript.</p>
    </div>
    <div class="img-container", style="background-color:#5FA2EB;">
      <%= image_tag("pindd-group.png", class: "full-photo", alt: "Group Layout")%>
    </div>
  </section>
</div>

app/views/static_pages/ploppy_cat.html.erb
<div class="project">
  <header class="project-header">
    <h1>Ploppy Cat</h1>
      <h3>Navigate your Nyan cat through space!</h3>
  </header>
  <section class="project-details">
    <p>Original code found <a href="http://www.uralozden.com/flappy/">here</a>.</p>
      <div id="screen" style="overflow: hidden;width:800px;margin:0 auto;">
      </div>
  </section>
</div>

app/views/static_pages/projects.html.erb
<section id="about-wrap">
  <div class="primary">
    <h1>Hi there!</h1>
    <p>My name is Joslyn. I'm a Seattle based Ruby on Rails developer with a <strong>strong</strong> affinity for the front-end and user experience.</p>
    <div id="about-photo">
      <%= image_tag("cssisawesome.jpg", alt: "Joslyn Rosbrook")%>
    </div>
    <p>When I'm not on my computer, you can find me on my yoga mat or curled up under a pile of blankets (but usually the computer finds its way there as well).</p>
  </div>
  <div class="secondary">
    <p>I recently graduated Code Fellows and now I'd like to use my passion for design and development to help <b>YOU</b>!</p>
      <h3>Let's chat?</h3>
         <div class="social-icons">
          <a href="http://www.twitter.com/joslynrosbrook" style="color:dodgerblue; font-size: 50px" class="fa fa-twitter"></a>
          <a href="http://www.github.com/meowmaste" style="color:indigo; font-size: 50px" class="fa fa-github"></a>
          <a href="http://www.linkedin.com/in/joslynrosbrook" style=" color:dimgray; font-size: 50px" class="fa fa-linkedin"></a>
        </div>
        <h5 class="email"><a href="mailto:jrosbrook@gmail.com">jrosbrook@gmail.com</a></h5>
  </div>
</section>
<section id="portfolio-wrap">
  <h1>Featured Work</h1>
  <h2>from the developer, <a href="http://joslynrosbrook.com/about">Joslyn Rosbrook</a></h2>
  <ul id="gallery">
    <li>
      <%= link_to "PINDD", pindd_path %>
        <%= image_tag("pindd.png", alt: "Post-It Note Driven Development")%>
    </li>
    <li>
      <%= link_to "Solar System", solarsystem_path %>
        <%= image_tag("solarsystem.png", alt: "Solar System")%>
    </li>
    <li>
      <%= link_to "Ploppy Cat", ploppycat_path %>
        <%= image_tag("ploppycat.png", alt: "Play Ploppy Cat")%>
    </li>
    <li>
      <%= link_to "Sync Cats", sync_cats_path %>
        <%= image_tag("sync-cats.png", alt: "Sync Cats")%>
    </li>
  </ul>
</section>

app/views/static_pages/solar_system.html.erb
<div class="project">
  <header class="project-header">
    <h1>Solar System</h1>
      <h3>A virtual tour of the solar system.</h3>
  </header>
  <section class="project-details">
    <div class="img-container", style="background-color:#EBFF00;">
      <%= image_tag("solarsystem.png", class: "main-photo", alt: "Solar System")%>
      <%= image_tag("solar-system-mobile.png", class: "mobile-photo", alt: "Phone Layout")%>
    </div>
    <div class="text-block">
      <p>After learning HTML5 and CSS3 and completing my Intro to JavaScript class, I was inspired to combine these skills into a <a href="http://solarsystem.joslynrosbrook.com">virutal tour of the solar system.</a></p>
      <p>This site represents a weekend's worth of work and features a fact about each main components of the solar system. As you hover over new parts of the site, a planet will jump from the side to the forefront, near its fact. If you click the page, a comet with shoot by.</p>
    </div>
    <div class="img-container", style="background-color:#42B85E;">
      <%= image_tag("solarsystem-full.png", class: "full-photo", alt: "Group Layout")%>
    </div>
  </section>
</div>

app/views/static_pages/sync_cats.html.erb
<div class="project">
  <header class="project-header">
    <h1>Sync Cats</h1>
      <h3>An app built to demonstrate HTTP streaming with the Sync Gem</h3>
  </header>
  <section class="project-details">
    <div class="text-block">
      <p>Sync Cats was an app built to demo HTTP streaming in class on a presentation about the <a href="https://github.com/chrismccord/sync">Sync Gem.</a></p>
      <p>At the end of my talk, I had my fellow students go to the Heroku app where each instance would create a Nyan cat. Each student could control their cat with the arrow keys and see in real-time the other student's cats roaming around space.</p>
      <p>For this app, I used the Sync Gem, Ruby on Rails, and JavaScript.</p>
      <p></p>
    </div>
    <div class="img-container", style="background-color:#C583D1;">
      <%= image_tag("sync-cats.png", class: "full-photo", alt: "Sync Cats")%>
    </div>
  </section>
</div>